version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ../app:/var/www/
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: yml_nginx

  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    volumes:
      - ../app:/var/www/
    depends_on:
      - db
    container_name: yml_app

  npm:
     image: node:14
     working_dir: /var/www/
     entrypoint: ["npm"]
     volumes:
       - "../app:/var/www/"
     container_name: uk_npm

  db:
    image: mariadb
    volumes:
      - ../tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
    ports:
      - 3306:3306
    container_name: yml_db

  #phpmyadmin:
   # image: phpmyadmin/phpmyadmin:latest
   # environment:
    #  PMA_HOST: db
     # PMA_USER: root
      #PMA_PASSWORD: root
    #ports:
     # - "8080:80"
    #container_name: yml_myadmin

networks:
  network1:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1450



